name: 'Deploy Azure Kubernetes Service'

on:
  push:
    branches:
      - main
    paths:
      - workload/azure-kubernetes-service/**

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    name: 'Deploy Azure Kubernetes Service'
    runs-on: ubuntu-latest
    environment: demo

    defaults:
      run:
        working-directory: ./workload/azure-kubernetes-service
        shell: bash

    steps:
      - name: Checkout repository from GitHub
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Initialize Terraform
        run: terraform init -backend-config="subscription_id=${{ vars.MANAGEMENT_SUBSCRIPTION_ID}}" -backend-config="resource_group_name=${{ vars.BACKEND_RESOURCE_GROUP_NAME }}" -backend-config="storage_account_name=${{ vars.BACKEND_STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=aks-demo" -backend-config="key=terraform.tfstate"
        env:
          ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ vars.MANAGEMENT_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}

      - name: Apply changes
        run: terraform apply -auto-approve -input=false
        env:
          ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ vars.MANAGEMENT_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
          TF_VAR_subscription_id: ${{ vars.AKS_DEMO_SUBSCRIPTION_ID }}